[package]
name = "rusty_constants"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = "1.0.219"
cargo-readme = "3.3.1"
utoipa = "5.3.1"
config = "0.15.11"
rand = "0.9.1"
html-escape = "0.2.13"
